### ISSUE TITLE
AshUUID.UUID Type does not respect constraint defaults

### ISSUE THREAD

**Issue by kernel-io** [zoonect-oss/ash_uuid#5]
AshUUID.UUID type does not respect the constraint default defined in the config.exs file.

config.exs
```elixir
config :myapp, :ash_uuid,
  version: 7,
  encoded?: true,
  prefixed?: false,
  migration_default?: true
```

Example resource:
```elixir
defmodule Fish do
  use Ash.Resource, data_layer: :embedded

  relationships do
    has_many :tag, Tag allow_nil?: false
  end

  attributes do
    uuid_attribute :id    
  end

  actions do
      update :remove_tag do
        argument :tag_id, :uuid, allow_nil?: false
        change manage_relationship(:tag_id, :tags, type: :remove)
      end
  end
end
```

I expect to be able to call `remove_tag` action and have it succeed. Currently it fails because the type is trying to prefix it with "id_".

After updatin `constraints/0` in AshUUID.UUID to read the config.exs config first, it acts as expected. Below is what works - albeit messy so would be good to clean up, also the default value of "" is only to keep the nimble opts happy about prefix not being able to be nil (which should be changed also).

```elixir
  @impl true
  def constraints() do
    Enum.map(@constraints, fn {key, value} ->
      {key, Keyword.replace(value, :default, AshUUID.Config.get_config([]) |> Map.get(key, ""))}
    end)
  end
```

**Comment by moissela** [comment]
This issue should be resolved in v0.6.0 just released.

Thanks for the feedback @kernel-io and let me know if it works as expected 😉
