### ISSUE TITLE
Migration adding default: nil to uuid after upgrade to 0.6.0

### ISSUE THREAD

**Issue by sezaru** [zoonect-oss/ash_uuid#6]
After upgrading ash_uuid from 0.5.0 to 0.6.0, I noticed that generating a new migration will generate this change to every table that uses ash_uuid:

```elixir
    alter table(:users) do
      modify :id, :uuid, default: nil
    end
```

This doesn´t seem correct since I don't want my primary key to be `nil`, is this on purpose, if so, what is the reasoning?

**Comment by moissela** [comment]
This issue should be resolved in v0.7.0 just released, sorry for the delay: I've been very busy.

Thanks for the feedback @sezaru and let me know if it works as expected 😉
